site_name: Ethical Hacker Academy
site_url: https://www.eha.net.br
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/eha_banner.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      example: fontawesome/brands/youtube
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true # Adiciona links permanentes aos cabeçalhos
      title: Índice
nav:
  - Início: index.md
  - Cursos:
    - Módulo de Acesso: cursos/modulodeacesso.md
    - Introdução ao Ethical Hacking: cursos/ieh.md
    - Introdução a Computação Forense: cursos/icf.md
  - Contatos:
    - E-mail: contatos/email.md
    - Endereço (Correspondência): contatos/endereco.md
  - Sobre: sobre.md
  - Ambiente EaD: https://ead.eha.net.br
  - Canal Youtube: https://www.youtube.com/@rkifrn
  - Instagram: https://www.instagram.com/ehaifrn 